name: Terraform Azure CI/CD

on:
  push:
    branches:
      - 'feature/pipeline1'
      

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:

  # =========================================================
  # FEATURE BRANCH / PR VALIDATION
  # =========================================================

  terraform-ci:

    name: Terraform Security Scan & Plan
    runs-on: ubuntu-latest

    steps:

      # -----------------------------------------------------
      # Checkout
      # -----------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------------------------
      # Azure Login using OIDC
      # -----------------------------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # -----------------------------------------------------
      # Terraform Setup
      # -----------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -----------------------------------------------------
      # Terraform Format Check
      # -----------------------------------------------------

      # - name: Terraform Format Check
        # run: terraform fmt -check -recursive

      # -----------------------------------------------------
      # TFLint
      # -----------------------------------------------------

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive

      # -----------------------------------------------------
      # Checkov - Terraform Security Scan
      # -----------------------------------------------------

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform

      # -----------------------------------------------------
      # Terraform Init
      # -----------------------------------------------------

      - name: Terraform Init
        run: terraform init

      # -----------------------------------------------------
      # Terraform Validate
      # -----------------------------------------------------

      - name: Terraform Validate
        run: terraform validate

      # -----------------------------------------------------
      # Terraform Plan
      # -----------------------------------------------------

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # -----------------------------------------------------
      # Upload Plan
      # -----------------------------------------------------

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan


  # =========================================================
  # MAIN BRANCH DEPLOYMENT
  # =========================================================

  terraform-apply:

    name: Terraform Apply
    runs-on: ubuntu-latest

    # GitHub Environment
    environment:
      name: production

    # Only run after CI job
    needs: terraform-ci

    # Run only when main branch is updated
    if: github.ref == 'refs/heads/main'

    steps:

      # -----------------------------------------------------
      # Checkout
      # -----------------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------------------------
      # Azure OIDC Login
      # -----------------------------------------------------

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # -----------------------------------------------------
      # Terraform Setup
      # -----------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -----------------------------------------------------
      # Terraform Init
      # -----------------------------------------------------

      - name: Terraform Init
        run: terraform init

      # -----------------------------------------------------
      # Terraform Plan
      # -----------------------------------------------------

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # -----------------------------------------------------
      # Terraform Apply
      # -----------------------------------------------------

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan